### PR TITLE
x1105 As ARA (Jasmine) I would like to able to the store source labware at the end of the section confirmation page as well as the slide and tubes created in the operation

### PR DESCRIPTION
**Pull request by sabrine33**

### CODE REVIEW

**Review by seenanair — COMMENTED** [review]
Looks ok.  Happy to approve once Cypress run passes in CI (may be the usual Cypress flakiness)

**Comment by sabrine33** [comment]
I am working on updating the cypress tests

**Review by seenanair — APPROVED** [review]
Looks ok.  Happy to approve once Cypress run passes in CI (may be the usual Cypress flakiness)

**Comment by sabrine33** [comment]
merged to devel

**Pull request merged**
