### PR TITLE
Fixed bug where comments were getting added to the request

### PR DESCRIPTION
**Pull request by BenTopping**
Found this bug when trying to create data to test the original sample processing views with

### CODE REVIEW

**Review by seenanair — COMMENTED** [review]
Great. Good Finding 👍

**Comment by khelwood** [comment]
Has someone tried this out locally and confirmed that it now works?

**Comment by seenanair** [comment]
> Has someone tried this out locally and confirmed that it now works?

@khelwood I am going to merge this along with others and going to test all of it together. Is it ok?

**Comment by khelwood** [comment]
> > Has someone tried this out locally and confirmed that it now works?
> 
> @khelwood I am going to merge this along with others and going to test all of it together. Is it ok?

Since it appears to be addressing a live bug, I am going to merge it into UAT instead of devel, so we can get it tested and released immediately.

**Comment by seenanair** [comment]
> > > Has someone tried this out locally and confirmed that it now works?
> > 
> > 
> > @khelwood I am going to merge this along with others and going to test all of it together. Is it ok?
> 
> Since it appears to be addressing a live bug, I am going to merge it into UAT instead of devel, so we can get it tested and released immediately.

Ok, I will test it and let you know

**Comment by khelwood** [comment]
I think Ben's already tested it, so I am going to merge into uat and deploy to uat.

**Comment by seenanair** [comment]
> I think Ben's already tested it, so I am going to merge into uat and deploy to uat.

Ok  👍

**Pull request merged**
