### PR TITLE
x1213 add new omero project from sgp management page

### PR DESCRIPTION
**Pull request by sabrine33**

### CODE REVIEW

**Review by khelwood — COMMENTED** [review]
I think _add omero project_ can only be performed by _admin_ users. I guess the option to add should only be visible if the user is admin, unless we're also changing the required user tier.

----
I'll update core to support endusers adding omero projects.

**Comment by khelwood** [comment]
@KatyTudor Currently only admin users can add a new omero project. Do you want regular users and/or endusers to be able to add them?

**Comment by KatyTudor** [comment]
@khelwood yes please, like the project and cost code on the SGP management page

**Review by khelwood — APPROVED** [review]

**Comment by sabrine33** [comment]
merged into devel

**Pull request merged**
