### PR TITLE
Reminder dialog display for RNAScope/IHC template

### PR DESCRIPTION
**Pull request by seenanair**

### CODE REVIEW

**Comment by khelwood** [comment]
My reading of Katy's request is that she just wants the message changing to "If you have submitted an RNAScope/IHC request, please complete the template for probes/antibody and fluorophore here, and upload it to STAN on the file management page linked to your request number."

**Comment by seenanair** [comment]
> My reading of Katy's request is that she just wants the message changing to "If you have submitted an RNAScope/IHC request, please complete the template for probes/antibody and fluorophore here, and upload it to STAN on the file management page linked to your request number."

So, you mean it is not required to display as a pop-up dialog(modal)?

**Comment by khelwood** [comment]
I don't think so.

**Comment by seenanair** [comment]
> I don't think so.

Please check the changes committed to devel  https://github.com/sanger/stan-client/commit/f11146e16f3851b8639f8f9a8a5c48f02985f999

**Pull request closed without merging**
