### PR TITLE
X821 - Priority field in SGP management page

### PR DESCRIPTION
**Pull request by seenanair**

### CODE REVIEW

**Comment by khelwood** [comment]
The client currently only sends an update work priority request if the work status is "Unstarted". In any other status, editing the work priority doesn't send a request.
It should work in any work status except for "completed" and "failed". For those, the UI should not let the user try and update the priority.

**Comment by seenanair** [comment]
> The client currently only sends an update work priority request if the work status is "Unstarted". In any other status, editing the work priority doesn't send a request. It should work in any work status except for "completed" and "failed". For those, the UI should not let the user try and update the priority.

Ok. I didn't know that such a condition existed. I will fix that.

**Comment by seenanair** [comment]
> The client currently only sends an update work priority request if the work status is "Unstarted". In any other status, editing the work priority doesn't send a request. It should work in any work status except for "completed" and "failed". For those, the UI should not let the user try and update the priority.

Fixed and pushed changes.

**Comment by khelwood** [comment]
When a work status is changed to "completed" or "failed", the core side clears its priority; but the client does not show that until you reload the page.

**Comment by seenanair** [comment]
> When a work status is changed to "completed" or "failed", the core side clears its priority; but the client does not show that until you reload the page.

Fixed

**Pull request merged**
